modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "moregrid"
version = "${mod_version}"
displayName = "Create: Power Components"
logoFile = "logo.png"
description = '''
Adds new miscellaneous PCB components to Create: Power Grid.
'''

[[dependencies.moregrid]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.moregrid]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.moregrid]]
modId = "powergrid"
type = "required"
versionRange = "[0.5.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moregrid]]
modId = "create"
type = "required"
versionRange = "[6.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.moregrid]]
modId = "architectury"
type = "required"
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"
